### ISSUE TITLE
STEAM SDA / CANT CONFIRMATION . CANT LOGIN AGAIN 

### ISSUE THREAD

**Issue by kirinforyou** [Jessecar96/SteamDesktopAuthenticator#865] opened 2023-06-23 17:34 UTC

**Comment by DOTBU** [comment] 2023-06-23 17:36
any fix?

**Comment by dyc3** [comment] 2023-06-23 17:41
This is a duplicate of every issue filed over the past couple of days. No, there is no fix, and no, it won't be fixed.

**Comment by Majestik56** [comment] 2023-06-23 19:16
I did not understand when it will be fixed and what to do   When will there be an update and how to make auntificator work on my computer ?

**Comment by CzarnaMamba** [comment] 2023-06-24 17:19
it will be fixed when it will be fixed

**Comment by MakcStudio** [comment] 2023-06-25 14:50
Use this fix: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859

**Closed** 2023-06-29 01:12 UTC
