### ISSUE TITLE
SDA does not remember Family View PIN

### ISSUE THREAD

**Issue by kevinvanrijn** [Jessecar96/SteamDesktopAuthenticator#529] opened 2018-07-29 11:06 UTC
After submitting the PIN in the trade confirmations window it refreshes and asks for the PIN again.

![screenshot 2018-07-29 12 57 08](https://user-images.githubusercontent.com/6368561/43365617-c3ef1490-932f-11e8-908f-9f9970f1a96c.png)

**Comment by AydievMansur** [comment] 2019-08-19 12:50
**fixed**

**Comment by kevinvanrijn** [comment] 2019-08-20 11:12
No it's not. SDA hasn't even released another updated since this issue was created.

The problem has only gotten worse, either due to Windows updates or changes made by Valve, it's not even possible to submit the PIN now.

**Comment by Jessecar96** [comment] 2020-01-28 21:52
Duplicate of #20

**Closed by Jessecar96** 2020-01-28 21:52 UTC
