### ISSUE TITLE
Steam Desktop Authenticator.exe - Not a valid Win32 application

### ISSUE THREAD

**Issue by excellproj** [Jessecar96/SteamDesktopAuthenticator#30] opened 2015-12-08 09:01 UTC
Hello!
When I launch the application, I get this error: "Steam Desktop Authenticator.exe - Not a valid Win32 application"
OS: WinXP SP3 x32 (VirtualBox)

**Comment by pipe01** [comment] 2015-12-08 13:26
Probably because you're using Windows XP. You can try building the code from XP.

**Comment by PFCKrutonium** [comment] 2015-12-08 18:55
Visual Studio 2015 can no longer build applications for XP. Your best bet is building it with GCC and telling GCC your building for XP.

**Comment by excellproj** [comment] 2015-12-08 19:46
I have visual studio 2010. Will it work?

**Comment by pipe01** [comment] 2015-12-08 19:49
I think the issue is that the program is built for x64. And about vs, I don't know, but just try if you can.

**Comment by PFCKrutonium** [comment] 2015-12-08 20:19
Well that x64 part too - I didn't think about arch, but on XP your almost always x86.

**Comment by excellproj** [comment] 2015-12-09 08:56
Where to get х86? Or it is necessary to build?

**Comment by hyt47** [comment] 2015-12-09 11:15
IT IS RECOMMENDED TO BUILD a x86 version!!!

Visual Studio > Build > Configuration Manager
in the project:
Steam Desketop manager | select "Any CPU" > New > 
  New Platform: x86
  Copy settings from: Any CPU
  Uncheck "Create new solution platforms"

do the same for "SteamAuth"

If u want i can give u a compiled version but that it is very unsafe for u. It's best to compile your own code!

**Comment by hyt47** [comment] 2015-12-09 12:38
I managed to compile a version for XP using Visual Studio 2013. I will add add instructions soon

**Comment by hyt47** [comment] 2015-12-09 13:38
Download version 0.2.3
------------------------
------------------------
https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
Extract



Download SteamAuth
------------------------
------------------------
https://github.com/Jessecar96/SteamAuth
Extract
copy the content from "SteamAuth-master" inside "SteamDesktopAuthenticator-0.2.3\lib\SteamAuth\"

final path "SteamDesktopAuthenticator-0.2.3\lib\SteamAuth\SteamAuth"



Open with Visual Studio (I used 2013)
------------------------
------------------------
Error
--------
Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=7.0.0.0, 
Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". 
Check to make sure the assembly exists on disk. If this reference is required by your 
code, you may get compilation errors.	SteamAuth

Repair
--------
1. Open up "SteamAuth > packages.config"
2. Delete the Newtonsoft.Json entry.
&lt;package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />

3. Save and Build
4. Re-add Newtonsoft.Json from NuGet.
	SteamAuth > Right click on "References" > Manage Nuget packages...
		find  Online > Json.Net > install
5.Build and run


warnings
------------
if u get any warnings is because u have a file opened up in visual studio
close it and recompile


Compile and test the x64 version
----------------------------------
----------------------------------
If it works fine, u can edit the code to make it for x86 widnows XP






----------------------------------
----------------------------------
----------------------------------
----------------------------------
Make the app for x86
----------------------------------
----------------------------------
Visual Studio > Build > Configuration Manager
in the project:
Steam Desketop manager | select "Any CPU" > New > 
  - New Platform: x86
  - Copy settings from: Any CPU
  - Uncheck "Create new solution platforms"

do the same for:
SteamAuth | select "Any CPU" > New > 
- ...




----------------------------------
----------------------------------
----------------------------------
----------------------------------
Make the app for widnows XP
----------------------------------
----------------------------------

Change to .Net Framework 4
---------------------------
In Visual Studio in the right > Solution Explorer > Steam Desktop Authentificator > 
 Properties > Application > .Net Framework 4

In Visual Studio in the right > Solution Explorer > SteamAuth > 
 Properties > Application > .Net Framework 4

Build > u will get some errors > Popup: Run the last successful build? NO


Steam Desktop Authentificator - Update Json.Net for net framework 4
--------------------------------------------------------------------
1. Open up "Steam Desktop Authentificator > packages.config"
2. Delete the Newtonsoft.Json entry.
" &lt;package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />"

3. Save and Close the file "packages.config"
4. Re-add Newtonsoft.Json from NuGet.
	SteamAuth > Right click on "References" > Manage Nuget packages...
		find  Online > Json.Net > install

5. Popup Message: The file was modified outside the source editor. Do you want to reload it?
Yes

6. Build > u will get some errors > Popup: Run the last successful build? NO


SteamAuth - Update Json.Net for net framework 4
--------------------------------------------------------------------
1. Open up "SteamAuth > packages.config"

do the same as above...



Error
--------
'System.Net.WebUtility' does not contain a definition for 'UrlEncode'

Repair
--------
.NET Framework 4.0 was already added

Addd a reference to System.Web using the "Add Reference" dialog.
SteamAuth > References > Add Reference > search for "System.Web"


Search in Entire solution "WebUtility.UrlEncode"
- when u find a match add at the top of the page: using System.Web;

- after u added to all that code search again and replace "WebUtility.UrlEncode" with "HttpUtility.UrlEncode"

Compile u will get a few warnings > the program will run ok




App error in Xp
-----------------
-----------------
application failed to initialize properly 0xc0000135

Repair
--------
install net framework 4
net framework 4 might ask u to install first Windows Imaging Component > install it


Done enjoy ^_^
-----------------
-----------------

**Comment by Jessecar96** [comment] 2015-12-09 18:31
Windows XP is not supported officially.

**Closed by Jessecar96** 2015-12-09 18:31 UTC
