### ISSUE TITLE
Need Hot Fix. SDA not loading Trade Confirmations.

### ISSUE THREAD

**Issue by pythhon1c** [Jessecar96/SteamDesktopAuthenticator#844] opened 2023-06-20 23:28 UTC
After Steam rebooted servers acceptConfirmationForObject method not work anymore.

I want to make donation aslo

**Comment by Giza** [comment] 2023-06-20 23:34
same

**Comment by Wolterhon** [comment] 2023-06-20 23:39
After the maintenance I get this when I try to view confirmations, just a blank screen
![изображение](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/23475741/57c5485a-cd78-4f30-b299-5de602c2258b)

**Comment by dyc3** [comment] 2023-06-20 23:41
You should not rely on SDA anymore. It's not being actively maintained. Go use the steam mobile app.

Steam has changed it's login mechanism, and SDA has not implemented it. You can still generate 2fa codes, so you are not locked out of your account, but you can't accept trade confirmations.

**Comment by Wolterhon** [comment] 2023-06-20 23:43
> It's not being actively maintained

I don't think that it's a problem. When a key feature breaks, someone comes and fixes it like it was two or three days ago. Switching to the mobile app will be so painful if I have to do it 😭

**Comment by dyc3** [comment] 2023-06-20 23:47
SDA has been extremely jank since the day it was released. Switch to the mobile app.

**Comment by omarmsn** [comment] 2023-06-20 23:49
is there a way to switch to the mobile app without a trade lock?

**Comment by dyc3** [comment] 2023-06-21 00:03
No.

**Comment by Wolterhon** [comment] 2023-06-21 00:04
> No.

Isn't there a way to at least make it 2 days (or maybe more, but still less than 15)?

**Comment by omarmsn** [comment] 2023-06-21 00:18
> > No.
> 
> Isn't there a way to at least make it 2 days (or maybe more, but still less than 15)?

afaik yes you're right, i just didnt try it myself yet

**Comment by ZangYUzhang** [comment] 2023-06-21 01:35
Steam has updated the confirmed url ? pls update a fix~~

**Comment by epichamman** [comment] 2023-06-21 01:51
Yeah guys how can we donate?

It would be great if can be fixed

**Comment by blwaveue** [comment] 2023-06-21 02:14
i have same problem

**Comment by Wolterhon** [comment] 2023-06-21 02:16
> SDA has been extremely jank since the day it was released. Switch to the mobile app.

I wouldn't be so harsh on it, it did its job, had to re-enter your password once in a while. Still miles better than using an emulator  / an actual phone

**Comment by maptong12** [comment] 2023-06-21 02:17
I have same problem. It ll be fix soon right ?

**Comment by Kurotaku-sama** [comment] 2023-06-21 02:24
> SDA has been extremely jank since the day it was released. Switch to the mobile app.

Thats not a good solution...

1. Not all ppl have a Smartphone
2. Not all ppl have a Smartphone that can run the Steam App

**Comment by TopDogger1** [comment] 2023-06-21 02:35
consider running a emulator with bluestacks as an alternative, wont have to deal with these issues like all of us are facing right now, that being said I would love to trade within the next 2 weeks

**Comment by epichamman** [comment] 2023-06-21 02:37
Trade confirmations are down for all 3rd party sites not just sda

**Comment by ZangYUzhang** [comment] 2023-06-21 02:44
Could anyone here fetch the Steam's new configuration request URL?

**Comment by malo4asov** [comment] 2023-06-21 02:47
Skinport solved this problem quickly
![skinport](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/137248147/a9ad30a6-ab38-49f8-a05d-96788a878031)
https://github.com/Jessecar96 please fix

**Comment by Wolterhon** [comment] 2023-06-21 03:03
> Could anyone here fetch the Steam's new configuration request URL?

https://github.com/juliarose/steam-tradeoffer-manager/commit/413bde52437635e8d11c8e6aaca740d78d691554

**Comment by AwkwordBG** [comment] 2023-06-21 03:25
Holy fock! 
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/44900770/54394dfc-50ae-4a74-8fb3-e07ff9289ea1)
Steam is being steam again. I dont know what kind of updates they do, most likely downgraders.

**Comment by isenlebi** [comment] 2023-06-21 03:50
Please fix

**Comment by davidsenio** [comment] 2023-06-21 04:27
> You should not rely on SDA anymore. It's not being actively maintained. Go use the steam mobile app.
> 
> Steam has changed it's login mechanism, and SDA has not implemented it. You can still generate 2fa codes, so you are not locked out of your account, but you can't accept trade confirmations.

Tens of thousands of people use your app daily. Someone because of the inability to use a smartphone, someone because of the use of a large number of accounts. Please consider raising money for further support of the program, you have no idea how many people are interested in this

**Comment by web3yc** [comment] 2023-06-21 04:35
> You should not rely on SDA anymore. It's not being actively maintained. Go use the steam mobile app.
> 
> Steam has changed it's login mechanism, and SDA has not implemented it. You can still generate 2fa codes, so you are not locked out of your account, but you can't accept trade confirmations.

We really need sda, many friends around me are using it, it is really useful and convenient.Thank you for your hard work on this project. I hope you don't give up on it

**Comment by NemesisPrime696** [comment] 2023-06-21 04:45
So apocalypse is finally here.

**Comment by Allower** [comment] 2023-06-21 04:48
Has anyone made a fork with a fix for trade confirmations yet?

**Comment by epichamman** [comment] 2023-06-21 04:48
> So apocalypse is finally here.

was gonna happen one day

**Comment by ZangYUzhang** [comment] 2023-06-21 05:14
Hey there, just a heads up! This project ain't costing us a dime, and the creator hasn't even set up a way for us to donate. So, y'know, we might need to chill and be a bit patient.

And btw, he dropped a note in the Version 1.0.10 releases saying, "SDA ain't dead." Fingers crossed, we should be seeing some fresh updates soon. Hang tight!

https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

**Comment by NemesisPrime696** [comment] 2023-06-21 05:26
> Hey there, just a heads up! This project ain't costing us a dime, and the creator hasn't even set up a way for us to donate. So, y'know, we might need to chill and be a bit patient.
> 
> And btw, he dropped a note in the Version 1.0.10 releases saying, "SDA ain't dead." Fingers crossed, we should be seeing some fresh updates soon. Hang tight!
> 
> https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
> 
> Yo, just so you know, the new request address for getting those unconfirmed transactions is: /mobileconf/getlist. And The response is now in JSON

These words - isn't it was like 3 years ago?

**Comment by ZangYUzhang** [comment] 2023-06-21 05:30
> 

Oh, you're right. But the final update Version 1.0.11 was on the last week.The future needs some hope. haha

**Comment by CAKyPA** [comment] 2023-06-21 05:34
> So apocalypse is finally here.

No real impact to me yet, but ETA:
`You have 07:16:29 to send the trade offer.`

**Comment by BUN-VictorJiang** [comment] 2023-06-21 06:43
There ars two new apis for trading list and confirmation.

**Comment by IRaevsky** [comment] 2023-06-21 07:44
okey new endpoint "/mobileconf/getlis" does not provide an easy solution to the problem :/
its no longer a 404 but it still cant give me
"Oh nooooes! There was a problem loading the confirmations page please try tour request again latee"

**Comment by therepower** [comment] 2023-06-21 10:14
> Has anyone made a fork with a fix for trade confirmations yet?

i will try now :D not really experienced with it but i'll give a try

**Comment by ThePro323** [comment] 2023-06-21 10:56
somebody knows any alternatives?

**Comment by therepower** [comment] 2023-06-21 10:57
As said before I am not experienced with C# but here is a small hotfix for urgent needs.

This only works with Automatic trade/market confirmation, you cannot select specific trades.

Remove the .txt extension, place it in lib/SteamAuth/SteamAuth and compile the project.

[SteamGuardAccount.cs.txt](https://github.com/Jessecar96/SteamDesktopAuthenticator/files/11816691/SteamGuardAccount.cs.txt)

**Comment by GrenzFeldwebel** [comment] 2023-06-21 11:22
Nothing is unclear, I do not have such files

**Comment by Wolterhon** [comment] 2023-06-21 11:24
> Nothing is unclear, I do not have such files

Cause you're meant to download the project (and not the release), change its code and then compile it yourself.

**Comment by GrenzFeldwebel** [comment] 2023-06-21 11:27
what project? I don't understand it. When will the program work? will there be a fix or what?

**Comment by Wolterhon** [comment] 2023-06-21 11:34
> what project?

SDA's github project. I meant its source code

> When will the program work?

When someone actually fixes it

**Comment by suckma420** [comment] 2023-06-21 11:44
> As said before I am not experienced with C# but here is a small hotfix for urgent needs.
> 
> This only works with Automatic trade/market confirmation, you cannot select specific trades.
> 
> Remove the .txt extension, place it in lib/SteamAuth/SteamAuth and compile the project.
> 
> [SteamGuardAccount.cs.txt](https://github.com/Jessecar96/SteamDesktopAuthenticator/files/11816691/SteamGuardAccount.cs.txt)

Can you make a diff so that the owner of the repo can easily merge it later?

**Comment by Wolterhon** [comment] 2023-06-21 11:45
> Can you make a diff so that the owner of the repo can easily merge it later?

It's not a complete fix though, so I don't think it'll be accepted

**Comment by suckma420** [comment] 2023-06-21 11:47
> > Can you make a diff so that the owner of the repo can easily merge it later?
> 
> It's not a complete fix though, so I don't think it'll be accepted

What doesn't work on this version though cause I havent checked it out yet, maybe I can figure out how to fix it later

**Comment by Wolterhon** [comment] 2023-06-21 11:47
> What doesn't work on this version though cause I havent checked it out yet, maybe I can figure out how to fix it later

He said he only fixed the auto-confirmation thing, he didn't touch the 'View Confirmations' window

**Comment by suckma420** [comment] 2023-06-21 11:49
Oh okay maybe ill look around later add create a pr

**Comment by Kemyada** [comment] 2023-06-21 11:54
I'm down bad. I cant compile that thing since i dont know how to and i dont have any compiler installed. Any options for me?

**Comment by therepower** [comment] 2023-06-21 11:54
> > What doesn't work on this version though cause I havent checked it out yet, maybe I can figure out how to fix it later
> 
> He said he only fixed the auto-confirmation thing, he didn't touch the 'View Confirmations' window

Steam only returns the confirmations as JSON now, so the view confirmations screen has to be recreated manually i think.

**Comment by therepower** [comment] 2023-06-21 11:55
> I'm down bad. I cant compile that thing since i dont know how to and i dont have any compiler installed. Any options for me?

I can share a precompiled version if you can trust

**Comment by Wolterhon** [comment] 2023-06-21 11:55
> Steam only returns the confirmations as JSON now, so the view confirmations screen has to be recreated manually i think.

Yeah, I guess so.

**Comment by therepower** [comment] 2023-06-21 11:57
> > As said before I am not experienced with C# but here is a small hotfix for urgent needs.
> > This only works with Automatic trade/market confirmation, you cannot select specific trades.
> > Remove the .txt extension, place it in lib/SteamAuth/SteamAuth and compile the project.
> > [SteamGuardAccount.cs.txt](https://github.com/Jessecar96/SteamDesktopAuthenticator/files/11816691/SteamGuardAccount.cs.txt)
> 
> Can you make a diff so that the owner of the repo can easily merge it later?

Fixing it would take a lot of time, steam no longer returns a confirmation page, just JSON data. 
Also adding/removing authenticator now needs an access token created by mobile app.
This module can do it but idk if there is one for .net

https://github.com/DoctorMcKay/node-steam-session#eauthtokenplatformtype

**Comment by fixp1** [comment] 2023-06-21 12:19
> > Я плохо себя чувствую. Я не могу скомпилировать эту вещь, потому что я не знаю, как это сделать, и у меня нет установленного компилятора. Есть варианты для меня?
> 
> Я могу поделиться предварительно скомпилированной версией, если вы можете доверять


Can you do for us?

**Comment by dognleass** [comment] 2023-06-21 12:43
@therepower do you have discord? if yes, could you add me at tired#5555 ? or just post the compiled file somewhere

**Comment by liquidzoot** [comment] 2023-06-21 12:45
@therepower add me on discord: liquidzoot and send me compiled file please..

**Comment by therepower** [comment] 2023-06-21 12:53
> @therepower do you have discord? if yes, could you add me at tired#5555 ? or just post the compiled file somewhere



> @therepower add me on discord: liquidzoot and send me compiled file please..

i will publish a temporary fix in around 30 mins here

**Comment by CAKyPA** [comment] 2023-06-21 12:57
Dodged the bullet, it's fixed on ArchiSteamFarm and they released the new version.
https://github.com/JustArchiNET/ArchiSteamFarm

Steps are:
- Follow the guide to transfer 2fa file. (Make sure it's not encrypted on SDA)
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Two-factor-authentication#steamdesktopauthenticator

- Then create new JSON configuration file with your 2fa account. Read the links first.
Make sure add Paused: True to your config file, otherwise it will try to farm steam trading cards.
Simplest JSON configuration file for the time being is (Enabled true, Paused true, SteamLogin, SteamPassword)
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Setting-up
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration

- Once ArchiSteamFarm loaded it's things, you will get blinking cursor.
Press "c" to enter command mode and enter "2faok [botname]" will confirm all the 2fa's. (2fano to decline all 2fa)
Remember it can only accept or decline all 2fa at ONCE. You can't select which to accept or decline.
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands#commands-1
Also ignore the "trade should be rejected" message, It's just a notification.

Remember ArchiSteamFarm is automation tool, so be careful.

**Comment by Kemyada** [comment] 2023-06-21 13:16
> Dodged the bullet, it's fixed on ArchiSteamFarm and they released the new version. https://github.com/JustArchiNET/ArchiSteamFarm
> 
> Steps are:
> 
> * Follow the guide to transfer 2fa file. (Make sure it's not encrypted on SDA)
>   https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Two-factor-authentication#steamdesktopauthenticator
> * Then create new JSON configuration file with your 2fa account. Read the links first.
>   Make sure add Paused: True to your config file, otherwise it will try to farm steam trading cards.
>   Simplest JSON configuration file for the time being is (Enabled true, Paused true, SteamLogin, SteamPassword)
>   https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Setting-up
>   https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration
> * Once ArchiSteamFarm loaded it's things, you will get blinking cursor.
>   Press "c" to enter command mode and enter "2faok [botname]" will confirm all the 2fa's. (2fano to decline all 2fa)
>   Remember it can only accept or decline all 2fa at ONCE. You can't select which to accept or decline.
>   https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands#commands-1
>   Also ignore the "trade should be rejected" message, It's just a notification.
> 
> Remember ArchiSteamFarm is automation tool, so be careful.

Is there a way to make it accept all 2fa periodically, like SDA does?

**Comment by CAKyPA** [comment] 2023-06-21 13:21
> Is there a way to make it accept all 2fa periodically, like SDA does?

Not familiar with ArchiSteamFarm, but you can probably automate the 2fa's. Check the link.
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Trading

**Comment by Kemyada** [comment] 2023-06-21 13:26
> > Is there a way to make it accept all 2fa periodically, like SDA does?
> 
> Not familiar with ArchiSteamFarm, but you can probably automate the 2fa's. Check the link. https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Trading

I'm far from being smart enough to be able to do it, and since there's no option to just add something like "AcceptAll2FA": True, somewhere... it's not viable for most of us, but thanks anyway.

**Comment by gdfsgdfg** [comment] 2023-06-21 13:49
Leave it to valve to break SDA after so many years.

**Comment by therepower** [comment] 2023-06-21 13:56
Check #854

**Comment by therepower** [comment] 2023-06-21 13:57
> > > Is there a way to make it accept all 2fa periodically, like SDA does?
> > 
> > 
> > Not familiar with ArchiSteamFarm, but you can probably automate the 2fa's. Check the link. https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Trading
> 
> I'm far from being smart enough to be able to do it, and since there's no option to just add something like "AcceptAll2FA": True, somewhere... it's not viable for most of us, but thanks anyway.

check my temporary fix @ #854

**Comment by SeriousSam0** [comment] 2023-06-22 11:25
> Skinport solved this problem quickly ![skinport](https://user-images.githubusercontent.com/137248147/247381592-a9ad30a6-ab38-49f8-a05d-96788a878031.PNG) @Jessecar96 please fix

is it working then it seems not so far

**Comment by danilfarm** [comment] 2023-06-22 21:16
I want to convert my mafile sda ​​to asf, but I get an error: Unexpected token 'U', "..."... is not valid JSON

**Comment by CAKyPA** [comment] 2023-06-23 10:33
> I want to convert my mafile sda ​​to asf, but I get an error: Unexpected token 'U', "..."... is not valid JSON

Make sure that your SDA is not encrypted/password protected.

**Comment by fixp1** [comment] 2023-06-24 11:35
need help 
Trying to add an account, after entering the credentials and getting the code, when I enter the code that I received in the mail, I always get this error (all the time)
![Безымянный](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/137295137/bb70a01c-c846-47cd-a152-6df2d418ceca)

**Comment by Jessecar96** [comment] 2023-06-29 18:40
Steam has removed the old endpoints that SDA was using to login and get confirmations. A new pre-release version is now available that implements the new methods: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

**Closed by Jessecar96** 2023-06-29 18:40 UTC

**Comment by jessecor96** [comment] 2023-07-05 12:06
@CAKyPA @fixp1 @PuklDukl @AwkwordBG @pythhon1c @Wolterhon @davidsenio @TopDogger1 

Version 1.0.13 (Includes the fix for the confirmations) https://bit.ly/SDA-1-0-13-V

A quick guide explaining I found, https://www.youtube.com/@ExistMoon or

**Comment by Wolterhon** [comment] 2023-07-05 12:07
> @CAKyPA @fixp1 @PuklDukl @AwkwordBG @pythhon1c @Wolterhon @davidsenio @TopDogger1
> 
> Version 1.0.13 (Includes the fix for the confirmations) https://bit.ly/SDA-1-0-13-V
> 
> A quick guide explaining https://www.youtube.com/@ExistMoon

Thanks a bunch for the reminder! I'm already using it :D It's been smooth

**Comment by jessecor96** [comment] 2023-07-05 12:08
> 

Perfect! The most recent link I sent is the pre-release which speeds it up a bunch and has a bunch of cool tweaks, would love your thoughts!

Happy it works!

**Comment by Wolterhon** [comment] 2023-07-05 12:10
> @Wolterhon >
> 
> Perfect! The most recent link I sent is the pre-release which speeds it up a bunch and has a bunch of cool tweaks, would love your thoughts!
> 
> Happy it works!

I knew something wasn't right. You're an impersonator

**Comment by allendaydayup** [comment] 2023-07-05 12:11
> > @Wolterhon >
> > Perfect! The most recent link I sent is the pre-release which speeds it up a bunch and has a bunch of cool tweaks, would love your thoughts!
> > Happy it works!
> 
> I knew something wasn't right. You're an impersonator

Be careful, don't click on the link he posted Be careful
